config/routes.rb
Rails.application.routes.draw do

  resources :shortened_links, :path => "/"
  resources :shortened_links do 
    resources :click, shallow: true
  end

end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :shortened_link
end

app/models/conversions/conversions.rb
module Conversions
  
end

app/models/conversions/decode_string.rb
module Conversions
  class DecodeString
    attr_accessor :string

    def initialize(string)
      self.string = string
    end

    def decode(base)
      self.string.to_i(base)
    end

  end
end

app/models/conversions/encode_integer.rb
module Conversions
  class EncodeInteger
    
    attr_accessor :integer

    def initialize(integer)
      self.integer = integer
    end

    def encode(base)
      self.integer.to_s(base)
    end

  end
end

app/models/shortened_link.rb
class ShortenedLink < ActiveRecord::Base
  has_many :clicks
  
  MIN_SEED = 100000
  DEFAULT_BASE = 32

  validates :url,
    presence: true
  
  validates :encoded_string,
    presence: true, 
    uniqueness: true

  validates :base,
    presence: true


  def self.build_from_uri(uri, base = DEFAULT_BASE)
    ShortenedLink.new(
      url: self.validate_url(uri),
      encoded_string: self.encoded_string(base),
      base: DEFAULT_BASE
      )
  end

  def shortened_url(base)
    File.join(base, self.encoded_string)
  end

  private
  def self.encoded_string(base)
    Conversions::EncodeInteger.new(encode_seed).encode(base)
  end

  def self.validate_url(uri)
    if Utilities::Http::url?(uri)
      uri
    else
      # this doesn't nearly guarantee that it's a proper url but close enough for now 
      uri.prepend("http://")
    end
  end

  def self.encode_seed
    next_available_id = ShortenedLink.maximum(:id).to_i.next

    # ensure minimum value and reduce liklihood of race condition
    # by adding an arbitrary value
    next_available_id + MIN_SEED

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/click_controller.rb
class ClickController < ApplicationController

  def create
    shortened_link = ShortenedLink.find(params[:shortened_link_id])

    click = shortened_link.clicks.build
    click.save
    redirect_to shortened_link.url

  end
end

app/controllers/shortened_links_controller.rb
require 'http'
class ShortenedLinksController < ApplicationController

  def index
    @shortened_links = ShortenedLink.all.reverse
    @shortened_link = ShortenedLink.new
  end

  def create

    shortened_link = ShortenedLink.build_from_uri(whitelist[:url])
    if shortened_link.save
      flash[:notice] = "Your link is updated"
    else 
      
      flash[:error] = "Unable to save link"
    end

    redirect_to [:shortened_links]
  end

  def show
    # instead of querying directly for the decoded ID, query by
    # encoded string for generalized base support
    shortened_link = ShortenedLink.where(encoded_string: params[:id]).first
    if shortened_link
      redirect_to shortened_link.url
    else 
      flash[:error] = "Sorry, this link does not exist!"
      redirect_to [:shortened_links]
    end
  end

  private

  def whitelist
    params.require(:shortened_link).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/click_helper.rb
module ClickHelper
end

app/helpers/shortened_links_helper.rb
module ShortenedLinksHelper
  def formatted_date(stamp)
    "#{time_ago_in_words(stamp)} ago"
  end

  def click_count(shortened_link)
    LinkClicks.new(shortened_link).click_count
  end
  
end

app/views/click/create.html.slim
h1 Click#create
p Find me in app/views/click/create.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Realreal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shortened_links/create.html.erb
<h1>ShortenedLinks#create</h1>
<p>Find me in app/views/shortened_links/create.html.erb</p>

app/views/shortened_links/index.html.slim
div class="top-bar"
  == "TheRealReal Link Shortener"
div class="shortener"
  
  div class="shortener__display-box"

        == form_for(@shortened_link, html: {class: "form-inline"}) do |f|
          .form-group

            .row
              .col-sm-10
                == f.text_field :url, label: false, class: "form-control shortened_link_url", placeholder: "Add long link"
              .col-sm-2
                == f.submit "Shorten!", class: "btn btn-default"

  div class="shortener__container"
    h4 class="center"
      = "All links"

    
    table class="table table-hover shortener__table table-condensed"
      thead
        tr
          th Link 
          th Added
          th Shortened
          th Clicks

      - @shortened_links.each do |link|
        tr
          td
            == link_to link.url, link.url
          td
            == formatted_date link.created_at
          td
            == link_to link.shortened_url(request.url),shortened_link_click_index_path(link), method: :post
          td 
            == click_count(link)

    

app/views/shortened_links/new.html.erb
<h1>ShortenedLinks#new</h1>
<p>Find me in app/views/shortened_links/new.html.erb</p>